# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "http://localhost:6600"
            - "http://localhost:3000"
            - "http://localhost:8000"
          allowed_headers:
            - "Content-Type"
            - "traceparent"
            - "tracestate"
            - "baggage"
            - "x-client-trace-id"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlp:
    # This should be the OTLP gRPC endpoint of the Jaeger service.
    # In your docker-compose, Jaeger is listening on 4317 for gRPC OTLP.
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

  extensions: []