receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins: ["http://localhost:6600", "http://localhost:3000", "http://localhost:8000"]
          allowed_headers: ["Content-Type", "traceparent", "tracestate", "baggage", "x-client-trace-id"]

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
    loglevel: info 
  prometheus:
    endpoint: "0.0.0.0:9464"  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [prometheus, logging]  # Choose what you need
