global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stock-tracker'
    static_configs:
      - targets: ['host.docker.internal:2222']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s
    #to remove any custom metrics
    # metric_relabel_configs:
    #   - source_labels: [__name__]
    #     regex: '.*otel.*'
    #     action: keep 
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'otel-collector-system-metrics'
    static_configs:
      - targets: ['otel-collector:9464']

