frontend:
  labels:
    app: frontend
    name: frontend
  deploy:
    name: frontend
    replicas: 1
    containers:
      name: frontend
      imagePullPolicy: Always
      image: abdullahedhii/opentel-demo-project:frontend-image
      ports:
        containerPort: 80
  service:
    name: frontend-service
    type: ClusterIP
    ports:
      protocol: TCP
      port: 6600
      targetPort: 80

backend:
  deploy:
    name: backend
    replicas: 1
    image: abdullahedhii/opentel-demo-project:backend-image
    imagePullPolicy: Always
    containers:
      name: backend
      ports:
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 2222
    volumeMounts:
      - name: shared-log
        mountPath: /fluentd/log

  pvc:
    name: shared-logs-pvc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

  service:
    name: backend-service
    type: ClusterIP
    ports:
      - name: http
        port: 8000
        targetPort: 8000
        protocol: TCP
      - name: metrics
        port: 2222
        targetPort: 2222
        protocol: TCP

kibana:
  name: kibana
  namespace: default
  image: docker.elastic.co/kibana/kibana:8.13.4
  replicas: 1
  service:
    type: ClusterIP
    port: 5601
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
  elasticsearch:
    hosts: https://elasticsearch-service:9200
    token: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjprSGdKYVdiZlFTU1FlZGxaQ1B1clNB
    cert: /usr/share/kibana/config/certs/http_ca.crt
    sslVerificationMode: none
  config:
    fleetEnabled: false
    apmEnabled: false
    monitoringEnabled: false
    reportingEnabled: false
