prometheus:
  replicaCount: 1
  
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  server:
    nameOverride: prometheus
    fullnameOverride: prometheus-service
    enabled: true
    service:
      type: ClusterIP
      port: 9090
      targetPort: 9090

    persistentVolume:
      enabled: false

  extraScrapeConfigs: |
      - job_name: 'otel-collector-system-metrics'
        metrics_path: '/metrics'
        static_configs:
          - targets: 
             - otel-collector-service:9464

      - job_name: 'cadvisor'
        static_configs:
          - targets: 
              - cadvisor-service:8080

      # - job_name: 'backend'
      #   static_configs:
      #     - targets: 
      #        - backend-service:2222

grafana:
  fullnameOverride: grafana-service

  operator:
    enabled: false

  admin:
    user: admin
    password: admin  # Will be required again on future upgrades unless using a custom secret

  grafana:
    service:
      type: ClusterIP
      port: 3000

    persistence:
      enabled: true
      size: 1Gi
      storageClass: Standard


frontend:
  labels:
    app: frontend
    name: frontend
  deploy:
    name: frontend
    replicas: 1
    containers:
      name: frontend
      imagePullPolicy: Always
      image: abdullahedhii/opentel-demo-project:frontend-image
      ports:
        containerPort: 80
  service:
    name: frontend-service
    type: ClusterIP
    ports:
      protocol: TCP
      port: 6600
      targetPort: 80

backend:
  deploy:
    name: backend
    replicas: 1
    image: abdullahedhii/opentel-demo-project:backend-image
    imagePullPolicy: Always
    containers:
      name: backend
      ports:
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 2222
    volumeMounts:
      - name: shared-log
        mountPath: /fluentd/log

  pvc:
    name: shared-logs-pvc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

  service:
    name: backend-service
    type: ClusterIP
    ports:
      - name: http
        port: 8000
        targetPort: 8000
        protocol: TCP
      - name: metrics
        port: 2222
        targetPort: 2222
        protocol: TCP

kibana:
  name: kibana
  namespace: default
  image: docker.elastic.co/kibana/kibana:8.13.4
  replicas: 1
  service:
    type: ClusterIP
    port: 5601
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
  elasticsearch:
    hosts: https://elasticsearch-service:9200
    token: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpmdDloUmRrRFJwQ08wa084c2R3NG1B
    cert: /usr/share/kibana/config/certs/http_ca.crt
    sslVerificationMode: none
  config:
    fleetEnabled: false
    apmEnabled: false
    monitoringEnabled: false
    reportingEnabled: false

jaeger:
 provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

 fullnameOverride: jaeger-service

 allInOne:
  enabled: true
  service:
    type: ClusterIP
    ports:
      - name: jaeger-ui
        port: 16686
        targetPort: 16686
      - name: jaeger-otlp
        port: 4317
        targetPort: 4317
      - name: jaeger-collector
        port: 14268
        targetPort: 14268

 collector:
  enabled: false

 agent:
  enabled: false

 query:
  enabled: false

 ingester:
  enabled: false

 cassandra:
  enabled: false

 storage:
  type: memory



ingress:
  enabled: true
  name: app-ingress
  rules:
    - host: grafana.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: grafana-service
          servicePort: 3000

    - host: frontend.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 6600
    - host: backend.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: backend-service
          servicePort: 8000
    - host: kibana.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: kibana-service
          servicePort: 5601
    - host: jaeger.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: jaeger-service-query
          servicePort: 16686
    - host: prometheus.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: prometheus-service
          servicePort: 9090
    - host: otel-collector.127.0.0.1.sslip.io
      paths:
        - path: /v1/traces
          pathType: Prefix
          serviceName: otel-collector-service
          servicePort: 4318
        - path: /v1/metrics
          pathType: Prefix
          serviceName: otel-collector-service
          servicePort: 4318
    # - host: cadvisor.127.0.0.1.sslip.io
    #   paths:
    #     - path: /
    #       pathType: Prefix
    #       serviceName: cadvisor-service
    #       servicePort: 8080
