postgresql:
 fullnameOverride: postgres
   
 auth:
    username: abdullah
    password: edhi
    postgresPassword: edhi
    database: mydb_1

 primary:
   persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

   podSecurityContext:
    enabled: true
    fsGroup: 1001

   containerSecurityContext:
    enabled: true
    runAsUser: 1001

   service:
    type: ClusterIP

 volumePermissions:
  enabled: true

 metrics:
  readinessProbe:
   enabled: true
   customCommand:
    command:
      - /bin/sh
      - -c
      - pg_isready -U abdullah -d mydb_1

  livenessProbe:
   enabled: true
   customCommand:
    command:
      - /bin/sh
      - -c
      - pg_isready -U abdullah -d mydb_1
      
elasticsearch:
  global:
    storageClass: "standard"
    security:
      allowInsecureImages: true
  fullnameOverride: "elasticsearch-service"
  
  clusterName: "Demo-Elastic"

  master:
    replicaCount: 1
    heapSize: 512m 
    resources:
     limits:
       memory: 2Gi
     requests:
       memory: 1Gi

  data:
    replicaCount: 1

  coordinating:
    replicaCount: 0

  ingest:
    enabled: false

  persistence:
    enabled: true
    size: 5Gi

  plugins: []


  esConfig:
    elasticsearch.yml: |
      cluster.name: Demo-Elastic
      node.name: ${HOSTNAME}
      #discovery.type: single-node
      network.host: 0.0.0.0
      http.port: 9200
      transport.port: 9300
      xpack.security.enabled: true
      # action.auto_create_index: .security*,.kibana*,.monitoring*,.watches*,.watcher-history*,.ml*
      action.auto_create_index: ".security-*,.kibana*,.monitoring*,.watches*,.watcher-history*,.ml*"


  volumePermissions:
    enabled: true

  extraVolumes:
    - name: config-volume
      configMap:
        name: elasticsearch-config

  extraVolumeMounts:
    - name: config-volume
      mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      subPath: elasticsearch.yml

  service:
    type: ClusterIP
    ports:
      restAPI: 9200
      transport: 9300

  security:
    enabled: true
    elasticPassword: edhi12
    tls:
      autoGenerated: true