apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
  labels:
    app: elasticsearch 
data:
  elasticsearch.yml: |
    cluster.name: Demo-Elastic
    node.name: ${HOSTNAME} 
    discovery.type: single-node 

    network.host: 0.0.0.0 
    http.port: 9200       
    transport.port: 9300  

    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

    xpack.graph.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
    
    xpack.security.authc.api_key.enabled: false 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g 
          resources:
            limits:
              memory: "2Gi" 
              cpu: "1000m"  
            requests:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml 
              subPath: elasticsearch.yml 
            - name: esdata
              mountPath: /usr/share/elasticsearch/data 
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config 
        - name: esdata 
          emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: default
  labels:
    app: elasticsearch 
spec:
  selector:
    app: elasticsearch 
  ports:
    - protocol: TCP
      name: http 
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: transport 
      port: 9300
      targetPort: 9300
  type: ClusterIP 