apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686 # UI
            - containerPort: 4317
            - containerPort: 14268
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: JAEGER_DISABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
    - name: jaeger-otlp
      port: 4317
      targetPort: 4317
    - name: jaeger-collector
      port: 14268
      targetPort: 14268
