apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
  labels:
    app: kibana 
data:
  kibana.yml: |
    
    server.host: "0.0.0.0" 
    server.port: 5601
    elasticsearch.hosts: ["http://elasticsearch-service:9200"] 
    xpack.fleet.enabled: false 
    xpack.apm.enabled: false 
    xpack.monitoring.enabled: false
    xpack.reporting.enabled: false
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.4 
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
          resources: 
            limits:
              memory: "1Gi" 
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts: 
            - name: config-volume
              mountPath: /usr/share/kibana/config/kibana.yml 
              subPath: kibana.yml 
      volumes: 
        - name: config-volume
          configMap:
            name: kibana-config 

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: default
  labels:
    app: kibana 
spec:
  selector:
    app: kibana 
  ports:
    - protocol: TCP
      name: http 
      port: 5601 
      targetPort: 5601 
  type: ClusterIP 