apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pvc.name }}
spec:
  accessModes:
{{ toYaml .Values.backend.pvc.accessModes | indent 4 }}
  resources:
{{ toYaml .Values.backend.pvc.resources | indent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploy.name }}
spec:
  replicas: {{ .Values.backend.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.deploy.name }}
    spec:
      imagePullSecrets:
            - name: regcred
      initContainers:
       - name: wait-for-postgres
         image: busybox:1.36
         command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: {{ .Values.backend.deploy.name }}
          image: {{ .Values.backend.deploy.image }}
          imagePullPolicy: {{ .Values.backend.deploy.imagePullPolicy }}
          ports:
{{- range .Values.backend.deploy.ports }}
            - containerPort: {{ .containerPort }}
{{- end }}
          volumeMounts:
{{ toYaml .Values.backend.deploy.volumeMounts | indent 12 }}
      volumes:
        - name: {{ .Values.backend.deploy.volumeMounts | first | dig "name" "shared-log" }}
          persistentVolumeClaim:
            claimName: {{ .Values.backend.pvc.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.deploy.name }}
  type: {{ .Values.backend.service.type }}
  ports:
{{- range .Values.backend.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
