apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
      cluster.name: Demo-Elastic
      node.name: ${HOSTNAME}
      #discovery.type: single-node
      network.host: 0.0.0.0
      http.port: 9200
      transport.port: 9300
      xpack.security.enabled: true
      # action.auto_create_index: .security*,.kibana*,.monitoring*,.watches*,.watcher-history*,.ml*
      action.auto_create_index: ".security-*,.kibana*,.monitoring*,.watches*,.watcher-history*,.ml*"